import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        System.out.print("Enter String");
        System.out.println();

        BuzzPuzzle puzzle = new BuzzPuzzle("1234");
        String input = br.readLine();
        System.out.println(puzzle.solve(input));
    }
}
